class MarketDataCache:
    def has(self, symbol, timeframe, start, end) -> bool: ...
    def load(self, symbol, timeframe, start, end) -> pd.DataFrame: ...
    def save(self, symbol, timeframe, start, end, df): ...